Added the scripts
OpenLake/Leaderboard-Pro pull request #12
Opened 2021-07-25 05:26 UTC by ArshpreetS

My scripts are by the name of:
1. personal.py --> To find the commits made by individual users
2. script.py --> which works for orgs

2021-07-25 11:51 UTC, KShivendu requested changes

2021-07-25 11:51 UTC, KShivendu commented on api/leaderboard/scripts/github api.txt
> +To get the information about the user's followers --> `curl https://api.github.com/users/{username}/followers`
These points can be easily figured out by reading the code. So I suggest you to remove these lines.

2021-07-25 11:51 UTC, KShivendu commented on api/leaderboard/scripts/script.py
> +		guys = {}
rename `guys` to `gh_user`

2021-07-25 11:51 UTC, KShivendu commented on api/leaderboard/scripts/script.py
> +			print(f'There were a total of {commits_that_day} commits on {reponame}!')
- Convert your scripts to functions
- Return JSON instead of printing the values

See Akshay's submission function in views.py for reference.

2021-08-01 08:54 UTC, ArshpreetS commented on api/leaderboard/scripts/script.py
> +		guys = {}
done

2021-08-01 08:54 UTC, ArshpreetS commented on api/leaderboard/scripts/script.py
> +			print(f'There were a total of {commits_that_day} commits on {reponame}!')
alrighty

2022-07-20 14:44 UTC, VickyMerzOwn commented
Can you squash the commits into one, with the right message? I'll then rebase and merge...

2022-07-20 14:48 UTC, ArshpreetS commented
okay.. I will do them soon

2022-10-18 09:26 UTC, closed without merging