Improved Nav and Footer
OpenLake/Leaderboard-Pro pull request #81
Opened 2023-10-01 12:55 UTC by SxxAq

## Purpose ✨

- Enhancement

## Details 📝

- Before
![Screenshot from 2023-10-01 18-20-25](https://github.com/OpenLake/Leaderboard-Pro/assets/98530202/3fbe5a67-e94a-4b5b-9571-a92e5b85321b)

- After
![Screenshot from 2023-10-01 18-20-37](https://github.com/OpenLake/Leaderboard-Pro/assets/98530202/caddfae8-db55-4fe2-b540-6c7480889f5a)

## Dependencies 🔗

None

## Future Improvements 🔭

- Signup and Login form Enhancement

## Mentions 👀

@krishnan05 

## Developer's checklist 📃
- [X] Followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html).
- [X] Properly commented the code.
- [X] No print statements in the code. 
- [X] All the functionalities are working properly.
- [X] Changes made are not breaking any other part of the project.
- [X] No UI/UX issues are present.
- [X] Relevant screenshots are added in the PR.
- [X] Followed the PR guidelines

2023-10-02 15:19 UTC, Akib-Vijapura commented
Fixes : #82

2023-10-04 17:45 UTC, Aditya062003 commented
Hey @SxxAq , your pull request certainly improves the current footer and navbar. However, as discussed in [issue 82](https://github.com/OpenLake/Leaderboard-Pro/issues/82) we wanted a new UI design for both navbar and footer.
While I am merging this PR, further modifications are highly appreciated

2023-10-04 17:47 UTC, Aditya062003 approved these changes

2023-10-04 17:51 UTC, Aditya062003 requested changes
Kindly resolve the conflict of package.json

2023-10-09 08:33 UTC, merged